version: "3"
services:

  quest_api:
    container_name: quest_api
    build:
      dockerfile: docker/Dockerfile
      context: .
    ports:
      - "8081:8080"
    depends_on:
      - consul
    environment:
      - spring.profiles.active=docker
      - APP_NAME=quest-api

  map_api:
    container_name: map_api
    build:
      dockerfile: docker/Dockerfile
      context: .
    ports:
      - "8082:8080"
    depends_on:
      - consul
    environment:
      - spring.profiles.active=docker
      - APP_NAME=map-api

  consul:
    container_name: consul
    image: consul:1.9.16
    ports:
      - "8500:8500"

